name: elearning
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_storage: ^2.0.2
  google_fonts: ^2.1.0
  url_launcher: ^6.0.4
  pull_to_refresh: ^2.0.0
  intl: ^0.17.0
  tiengviet: ^0.5.0
  webview_flutter: ^2.0.8
  transparent_image: ^2.0.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  logger: ^1.0.0
  # system_settings: ^2.0.0
  fluttertoast: ^8.0.7
  get: ^4.1.4
  flutter_svg: ^0.23.0+1
  get_cli: ^1.6.0
  event_bus: ^2.0.0
  sentry_flutter: ^6.2.0
  app_settings: ^4.1.1
  package_info: ^2.0.2
  connectivity: ^3.0.6
  flutter_dotenv: ^5.0.0
  cached_network_image: ^3.1.0
  # flutter_pdfview: ^1.2.1
  carousel_slider: ^4.0.0
  video_player: ^2.2.5
  flutter_html: any
  # file_picker: ^4.0.2
  socket_io_client: ^1.0.2
  path_provider: ^2.0.7
  http: ^0.13.3
  page_turn: ^1.0.1
  assets_audio_player: ^3.0.3+6
  bordered_text: ^2.0.0
  agora_rtc_engine: ^4.0.7
  # agora_rtm: ^1.0.1
  permission_handler: ^8.3.0
  modal_bottom_sheet: ^2.0.0
  flutter_slidable: ^1.1.0
  flutter_countdown_timer: ^4.1.0
  image_picker: ^0.8.4+4
  photo_view: ^0.13.0
  awesome_dialog: ^2.1.1
  flutter_rating_bar: ^4.0.0
  record_mp3: ^3.0.0
  async: ^2.8.1
  path: ^1.8.0
  timeago: ^3.1.0
  draggable_scrollbar: ^0.1.0
  audioplayers: ^0.20.1
  smooth_page_indicator: ^1.0.0+2
  chewie: ^1.2.2
  flutter_widget_from_html: ^0.8.4
  flutter_tts: ^3.3.3
  # pull_to_refresh: ^2.0.0
  percent_indicator: ^4.0.0
  # chewie: ^1.2.2
  provider: ^5.0.0
  speech_to_text: ^5.4.2
  uni_links: ^0.5.1
  scrollable_positioned_list: ^0.2.3
  crypto: ^3.0.0
  screenshot: ^1.2.3
  pdf: ^3.6.5
  adhara_socket_io: ^1.0.1+1
  ext_storage: ^1.0.3
  device_info_plus: ^3.2.1
  flutter_screenutil: ^5.1.0
  flutter_inappwebview: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/
    - assets/mp3/
    - assets/minigame/
    - .env.dev
    - .env
